version: '3.1'

services:
  elasticsearch:
    container_name: wineries-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
      - "9200:9200"
    environment:
      - node.name=search01
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    networks:
      - elastic

networks:
  elastic:
    driver: bridge